project:
  type: website
  output-dir: docs

website:
  title: "conbrad.ca"
  open-graph: true
  navbar:
    left:
    - about.qmd 
    tools:
      - icon: github
        href: https://github.com/conbrad
      - icon: linkedin
        href: https://www.linkedin.com/in/conorgbrady/
format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css



